### ISSUE TITLE
Sub-stories are order alphabetical by default when using mdx

### ISSUE THREAD

**Issue by bodograumann** [storybookjs/builder-vite#264]
By default, stories in a folder should be ordered by there definition order.
Instead they are sorted alphabetically.
See e.g. here: https://github.com/bodograumann/storybook-jest-vite-interop, where `Button 1 / ZZZ` is defined before `Button 1 / AAA`, but the order in the storybook is reversed.
![Screenshot_20220228-092303](https://user-images.githubusercontent.com/1223583/155949111-b15f82af-654a-493d-ab4c-7c501dfb834d.png)

**Comment by joshwooding** [comment]
Might be related to https://github.com/eirslett/storybook-builder-vite/issues/227

**Comment by joshwooding** [comment]
This should be fixed if you use storybook 6.4.20+

**Comment by IanVS** [comment]
This is still an issue with 6.5.0-beta.8 and the latest vite builder. 

<img width="390" alt="image" src="https://user-images.githubusercontent.com/4616705/168453121-c6029d20-200e-48e6-bb85-438288df7b04.png">
